REG_ENTITY(Player		  , "EPlayer"		  )
REG_ENTITY(Bullet		  , "EBullet"		  )
REG_ENTITY(Button		  , "EButton"		  )
REG_ENTITY(BSO			  , "EBSO"			  )
REG_ENTITY(StaticObstacle , "EStaticObstacle" )
REG_ENTITY(FinishScene    , "EFinishScene"    )
REG_ENTITY(DynamicObstacle, "EDynamicObstacle")