#ifndef UGINE_MAIN_H
#define UGINE_MAIN_H

#include "array.h"
#include "affector.h"
//#include "bone.h"
#include "camera.h"
#include "circlecollision.h"
#include "collision.h"
#include "collisionManager.h"
#include "collisionPixelData.h"
#include "emitter.h"
#include "glyph.h"
#include "font.h"
#include "glinclude.h"
#include "image.h"
#include "InputManager.h"
//#include "isometricmap.h"
//#include "isometricscene.h"
//#include "isometricsprite.h"
//#include "map.h"
//#include "mapscene.h"
#include "math.h"
#include "parallaxscene.h"
#include "particle.h"
#include "pixelcollision.h"
#include "rectcollision.h"
#include "renderer.h"
#include "resourcemanager.h"
#include "scene.h"
#include "screen.h"
//#include "skeletonsprite.h"
#include "sprite.h"
#include "string.h"
#include "types.h"

#endif
